language: node_js
sudo: true
node_js:
  - 0.8
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=chromium-browser
  - npm install
script: ./node_modules/.bin/grunt karma:unit