language: node_js
node_js:
  - 0.12
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start - nohup bash -c
  - export CHROME_BIN=chromium-browser
  - npm install
  - ./node_modules/.bin/webdriver-manager update--standalone
  - ./nodemodules/protractor/bin/webdriver-manager start 2>&1 & - sleep 5
script: ./node_modules/.bin/grunt e2eTest
